# fly.toml app configuration file generated for roy-is-a-bridge-tiddlywiki on 2024-08-16T15:48:03+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'myapp'
primary_region = 'lhr'

[build]

[[mounts]]
  source = 'mydata'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
