# fly.toml app configuration file generated for roy-is-a-bridge-tiddlywiki-autumn-leaf-3649 on 2024-08-16T18:20:53+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'roy-is-a-bridge-tiddlywiki-autumn-leaf-3649'
primary_region = 'lhr'

[build]

[[mounts]]
  source = 'tiddlywiki_data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
